export const MAX_HEIGHT = 80
export const PADDING_HORIZONTAL = 24
export const PADDING_VERTICAL = 16
export const HIDDEN_ATTRIBUTE_VALUE_LENGTH = 10
export const BULLET_UNICODE_CHARACTER = '\u2022'
export const HIDDEN_ATTRIBUTE_VALUE = Array(HIDDEN_ATTRIBUTE_VALUE_LENGTH).fill(BULLET_UNICODE_CHARACTER).join('')
